packages:
  - client
  - server
  - mcp
  - nubbi-blog

overrides:
  mongodb: 6.21.0

packageExtensions:
  lucide-react:
    peerDependencies:
      "@types/react": "*"

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
