import type { LanguageFn } from "lowlight";

export const mermaidLanguage: LanguageFn = (hljs) => ({
  name: "Mermaid",
  aliases: ["mmd"],
  keywords: {
    keyword: [
      "flowchart",
      "graph",
      "subgraph",
      "end",
      "direction",
      "sequenceDiagram",
      "classDiagram",
      "stateDiagram",
      "stateDiagram-v2",
      "erDiagram",
      "journey",
      "gantt",
      "pie",
      "quadrantChart",
      "requirementDiagram",
      "gitGraph",
      "mindmap",
      "timeline",
      "zenuml",
      "sankey-beta",
      "xychart-beta",
      "packet-beta",
      "block-beta",
      "architecture-beta",
      "participant",
      "actor",
      "autonumber",
      "activate",
      "deactivate",
      "loop",
      "alt",
      "else",
      "opt",
      "par",
      "and",
      "rect",
      "critical",
      "option",
      "break",
      "class",
      "namespace",
      "state",
      "note",
      "link",
      "click",
      "callback",
      "style",
      "classDef",
      "linkStyle",
      "title",
      "section",
      "dateFormat",
      "axisFormat",
      "tickInterval",
      "excludes",
      "includes",
      "todayMarker",
    ].join(" "),
    literal: "TB TD BT RL LR true false null",
  },
  contains: [
    {
      scope: "meta",
      begin: /%%\{/,
      end: /\}%%/,
    },
    {
      scope: "comment",
      begin: /%%(?!\{)/,
      end: /$/,
    },
    hljs.QUOTE_STRING_MODE,
    hljs.APOS_STRING_MODE,
    {
      scope: "symbol",
      match: /<-->|<--|-->|---|--[ox]|[ox]--[ox]?|-\.->|-\.-|==>|===|~~~/,
    },
    {
      scope: "number",
      begin: /\b\d+(?:\.\d+)?\b/,
    },
  ],
});
