import { Platform, StyleSheet } from "react-native";
import { colors } from "../../theme";

// 设置页相关样式：解锁页、Tab、表单、MCP 服务列表等共用。
export const settingsStyles = StyleSheet.create({
  safeArea: { backgroundColor: colors.background, flex: 1 },
  flex: { flex: 1 },
  center: { alignItems: "center", flex: 1, justifyContent: "center" },
  modalHeader: { alignItems: "center", backgroundColor: colors.surface, borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 58, paddingLeft: 16, paddingRight: 6 },
  modalTitle: { color: colors.text, flex: 1, fontSize: 18, fontWeight: "700" },
  unlock: { flex: 1, gap: 16, justifyContent: "center", padding: 24 },
  unlockIcon: { alignItems: "center", alignSelf: "center", backgroundColor: colors.primarySoft, borderRadius: 8, height: 54, justifyContent: "center", width: 54 },
  tabs: { backgroundColor: colors.surface, flexDirection: "row", padding: 8 },
  tab: { alignItems: "center", borderRadius: 6, flex: 1, flexDirection: "row", gap: 7, height: 40, justifyContent: "center" },
  tabActive: { backgroundColor: colors.primarySoft },
  tabText: { color: colors.muted, fontSize: 14, fontWeight: "600" },
  tabTextActive: { color: colors.primary },
  scrollContent: { gap: 14, padding: 14, paddingBottom: 34 },
  panel: { gap: 16 },
  providerRow: { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, paddingBottom: 12 },
  itemTitle: { color: colors.text, fontSize: 15, fontWeight: "700" },
  itemSubtitle: { color: colors.muted, fontSize: 12, marginTop: 3 },
  fieldLabel: { color: colors.text, fontSize: 14, fontWeight: "600" },
  modelLabelRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: -14 },
  modelList: { marginTop: -7 },
  modelChip: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 6, borderWidth: 1, marginRight: 8, paddingHorizontal: 10, paddingVertical: 7 },
  modelChipActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
  modelChipText: { color: colors.muted, fontSize: 12 },
  modelChipTextActive: { color: colors.primary, fontWeight: "600" },
  notice: { backgroundColor: colors.primarySoft, borderRadius: 6, color: colors.primary, fontSize: 13, padding: 11 },
  dangerNotice: { backgroundColor: colors.dangerSoft, color: colors.danger },
  backRow: { alignItems: "center", flexDirection: "row", gap: 5, minHeight: 40 },
  backText: { color: colors.primary, fontSize: 16, fontWeight: "700" },
  headersTitleRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: -12 },
  headerEditor: { alignItems: "flex-end", borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 4, paddingBottom: 14 },
  headerFields: { flex: 1, gap: 10 },
  switchRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  actionsRow: { flexDirection: "row", gap: 10 },
  serverItem: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 6, borderWidth: 1, padding: 12 },
  serverTopRow: { alignItems: "flex-start", flexDirection: "row", gap: 10 },
  serverNameRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  serverUrl: { color: colors.muted, fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace", fontSize: 11, marginTop: 6 },
  httpBadge: { backgroundColor: colors.primarySoft, borderRadius: 4, color: colors.primary, fontSize: 10, fontWeight: "700", paddingHorizontal: 6, paddingVertical: 2 },
  serverActions: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "flex-end", marginTop: 12, paddingTop: 4 },
  emptyText: { color: colors.muted, padding: 32, textAlign: "center" },
});
