import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const markdownStyles = {
  body: { color: colors.text, fontSize: 15, lineHeight: 23 },
  paragraph: { marginBottom: 8, marginTop: 0 },
  code_inline: { backgroundColor: colors.codeBackground, color: colors.text },
  fence: { backgroundColor: colors.codeBackground, borderColor: colors.border, color: colors.text },
  link: { color: colors.primary },
};

export const chatStyles = StyleSheet.create({
  safeArea: { backgroundColor: colors.background, flex: 1 },
  flex: { flex: 1 },
  header: { alignItems: "center", backgroundColor: colors.surface, borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 58, paddingHorizontal: 6 },
  headerTitle: { flex: 1, paddingHorizontal: 5 },
  headerTitleText: { color: colors.text, fontSize: 15, fontWeight: "700" },
  headerSubtitle: { color: colors.muted, fontSize: 11, marginTop: 2 },
  center: { alignItems: "center", flex: 1, justifyContent: "center" },
  empty: { alignItems: "center", flex: 1, justifyContent: "center", padding: 34 },
  emptyIcon: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 8, height: 60, justifyContent: "center", width: 60 },
  emptyTitle: { color: colors.text, fontSize: 21, fontWeight: "700", marginTop: 18 },
  emptyText: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 8, textAlign: "center" },
  messages: { gap: 18, padding: 16 },
  messageRow: { alignItems: "flex-start" },
  userMessageRow: { alignItems: "flex-end" },
  message: { minWidth: 32 },
  userMessage: { backgroundColor: colors.userBubble, borderRadius: 8, maxWidth: "86%", paddingHorizontal: 14, paddingVertical: 10 },
  assistantMessage: { width: "100%" },
  userText: { color: colors.text, fontSize: 15, lineHeight: 22 },
  capability: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 6, borderWidth: 1, flexDirection: "row", gap: 9, marginBottom: 8, padding: 10 },
  capabilityTitle: { color: colors.text, fontSize: 12, fontWeight: "700" },
  capabilityText: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 2 },
  errorText: { backgroundColor: colors.dangerSoft, borderRadius: 6, color: colors.danger, padding: 10 },
  bannerError: { backgroundColor: colors.dangerSoft, color: colors.danger, fontSize: 12, paddingHorizontal: 14, paddingVertical: 8, textAlign: "center" },
  composerArea: { backgroundColor: colors.surface, borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, paddingHorizontal: 10, paddingTop: 9 },
  composer: { alignItems: "flex-end", borderColor: colors.border, borderRadius: 8, borderWidth: 1, flexDirection: "row", padding: 5 },
  composerInput: { color: colors.text, flex: 1, fontSize: 15, lineHeight: 21, maxHeight: 112, minHeight: 42, paddingHorizontal: 9, paddingVertical: 10 },
  sendButton: { backgroundColor: colors.primary, height: 40, width: 40 },
  stopButton: { backgroundColor: colors.primarySoft, height: 40, width: 40 },
  disclaimer: { color: colors.muted, fontSize: 10, paddingBottom: 5, paddingTop: 5, textAlign: "center" },
  modalHeader: { alignItems: "center", borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 58, paddingLeft: 16, paddingRight: 6 },
  modalTitle: { color: colors.text, flex: 1, fontSize: 18, fontWeight: "700" },
  newConversation: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 6, flexDirection: "row", gap: 9, margin: 12, minHeight: 46, paddingHorizontal: 14 },
  newConversationText: { color: colors.primary, fontSize: 15, fontWeight: "700" },
  historyList: { paddingHorizontal: 12 },
  historyItem: { alignItems: "center", borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 68, paddingVertical: 8 },
  historyTitle: { color: colors.text, fontSize: 15, fontWeight: "600" },
  historyDate: { color: colors.muted, fontSize: 11, marginTop: 5 },
  emptyHistory: { color: colors.muted, padding: 40, textAlign: "center" },
});
